name: Page-analizator-CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
     
    services:
      postgres:
        image: postgres:10.8
        ports:
        - 5432:5432
        
    steps:
    - uses: actions/checkout@v2
      
    - name: PHP Setup
      uses: shivammathur/setup-php@v1

    - name: Composer Install
      run: make install

    - name: check linter 
      run: make lint

    - name: Tests
      run: make test
